# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/DELL/Desktop/CW4.team/adc_8channel_zyw/adc_8channel_zyw_1/adc_8channel_zyw_1.srcs/sources_1/ip/eth_data_fifo/eth_data_fifo.xci
# IP: The module: 'eth_data_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DELL/Desktop/CW4.team/adc_8channel_zyw/adc_8channel_zyw_1/adc_8channel_zyw_1.srcs/sources_1/ip/eth_data_fifo/eth_data_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_data_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/DELL/Desktop/CW4.team/adc_8channel_zyw/adc_8channel_zyw_1/adc_8channel_zyw_1.srcs/sources_1/ip/eth_data_fifo/eth_data_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/DELL/Desktop/CW4.team/adc_8channel_zyw/adc_8channel_zyw_1/adc_8channel_zyw_1.srcs/sources_1/ip/eth_data_fifo/eth_data_fifo.xci
# IP: The module: 'eth_data_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DELL/Desktop/CW4.team/adc_8channel_zyw/adc_8channel_zyw_1/adc_8channel_zyw_1.srcs/sources_1/ip/eth_data_fifo/eth_data_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/DELL/Desktop/CW4.team/adc_8channel_zyw/adc_8channel_zyw_1/adc_8channel_zyw_1.srcs/sources_1/ip/eth_data_fifo/eth_data_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
