# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo_tcp/fifo_tcp.xci
# IP: The module: 'fifo_tcp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo_tcp/fifo_tcp.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_tcp'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo_tcp/fifo_tcp_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_tcp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo_tcp/fifo_tcp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_tcp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo_tcp/fifo_tcp.xci
# IP: The module: 'fifo_tcp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo_tcp/fifo_tcp.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_tcp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo_tcp/fifo_tcp_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_tcp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo_tcp/fifo_tcp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_tcp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
