# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcku040-ffva1156-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.cache/wt [current_project]
set_property parent.project_path E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/SiTCP_Netlist_for_Kintex_UltraScale-master/SiTCP_XCKU_32K_BBT_V110.V
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/SiTCP_Netlist_for_Kintex_UltraScale-master/TIMER.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/SiTCP_Netlist_for_Kintex_UltraScale-master/WRAP_SiTCP_GMII_XCKU_32K.V
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/adc_board.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/adc_spi.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/arp_cache.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/arp_rx.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/arp_tx.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/crc.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/data_package.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/data_processing.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/new/data_sample_inv.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/new/ethernet.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/new/ethernet_test.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/new/gmii_arbi.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/gmii_rx_buffer.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/gmii_tx_buffer.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/icmp_reply.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/ip_rx.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/ip_tx.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/ip_tx_mode.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/lut_config.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/mac_rx.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/mac_rx_top.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/mac_test.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/mac_top.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/mac_tx.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/mac_tx_mode.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/mac_tx_top.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/src/sd_card/sd_card_cmd.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/src/sd_card/sd_card_sec_read_write.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/src/sd_card_test.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/src/sd_card/sd_card_top.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/new/sitcp_test.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/smi_config.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/smi_read_write.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/spi_config.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/spi_master.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/udp_rx.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/udp_tx.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/imports/new/util_gmii_to_rgmii.v
  E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/sources_1/new/top_1.v
}
read_ip -quiet E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/eth_data_fifo/eth_data_fifo.xci
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/eth_data_fifo/eth_data_fifo.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/eth_data_fifo/eth_data_fifo_ooc.xdc]

read_ip -quiet E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_4/ila_4.xci
set_property used_in_synthesis false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_4/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_4/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_4/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_4/ila_4_ooc.xdc]

read_ip -quiet E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_2/ila_2.xci
set_property used_in_synthesis false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_2/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_2/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_2/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_2/ila_2_ooc.xdc]

read_ip -quiet E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/len_fifo/len_fifo.xci
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/len_fifo/len_fifo.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/len_fifo/len_fifo_ooc.xdc]

read_ip -quiet E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_3/ila_3.xci
set_property used_in_synthesis false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_3/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_3/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_3/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_3/ila_3_ooc.xdc]

read_ip -quiet E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/icmp_rx_ram_8_256/icmp_rx_ram_8_256.xci
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/icmp_rx_ram_8_256/icmp_rx_ram_8_256_ooc.xdc]

read_ip -quiet E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo5/fifo5.xci
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo5/fifo5.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo5/fifo5_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo5/fifo5_ooc.xdc]

read_ip -quiet E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_6/ila_6.xci
set_property used_in_synthesis false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_6/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_6/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_6/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_6/ila_6_ooc.xdc]

read_ip -quiet E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/udp_tx_data_fifo/udp_tx_data_fifo.xci
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/udp_tx_data_fifo/udp_tx_data_fifo.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/udp_tx_data_fifo/udp_tx_data_fifo_ooc.xdc]

read_ip -quiet E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/udp_rx_ram_8_2048/udp_rx_ram_8_2048.xci
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/udp_rx_ram_8_2048/udp_rx_ram_8_2048_ooc.xdc]

read_ip -quiet E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/sys_clk_mmcm/sys_clk_mmcm.xci
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/sys_clk_mmcm/sys_clk_mmcm_board.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/sys_clk_mmcm/sys_clk_mmcm.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/sys_clk_mmcm/sys_clk_mmcm_ooc.xdc]

read_ip -quiet E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/udp_checksum_fifo/udp_checksum_fifo.xci
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/udp_checksum_fifo/udp_checksum_fifo.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/udp_checksum_fifo/udp_checksum_fifo_ooc.xdc]

read_ip -quiet E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

read_ip -quiet E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_5/ila_5.xci
set_property used_in_synthesis false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_5/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_5/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_5/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_5/ila_5_ooc.xdc]

read_ip -quiet E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo4/fifo4.xci
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo4/fifo4.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo4/fifo4_ooc.xdc]

read_ip -quiet E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo_ttt/fifo_ttt.xci
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo_ttt/fifo_ttt.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo_ttt/fifo_ttt_ooc.xdc]

read_ip -quiet E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo2/fifo2.xci
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo2/fifo2.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo2/fifo2_ooc.xdc]

read_ip -quiet E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo3/fifo3.xci
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo3/fifo3.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo3/fifo3_ooc.xdc]

read_ip -quiet E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_1/ila_1.xci
set_property used_in_synthesis false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/ila_1/ila_1_ooc.xdc]

read_ip -quiet E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.xci
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/ip_0/synth/gig_ethernet_pcs_pma_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/ip_0/synth/gig_ethernet_pcs_pma_0_gt.xdc]

read_ip -quiet e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo_tcp/fifo_tcp.xci
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo_tcp/fifo_tcp.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo_tcp/fifo_tcp_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/ip/fifo_tcp/fifo_tcp_ooc.xdc]

read_edif E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/sources_1/imports/SiTCP_Netlist_for_Kintex_UltraScale-master/SiTCP_XCKU_32K_BBT_V110.edf
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/constrs_1/imports/new/adc_ethernet.xdc
set_property used_in_implementation false [get_files E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/constrs_1/imports/new/adc_ethernet.xdc]

read_xdc E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/constrs_1/imports/SiTCP_Netlist_for_Kintex_UltraScale-master/EDF_SiTCP_constraints.xdc
set_property used_in_implementation false [get_files E:/vivadoprojects/adcether/adc_8channel_zyw_3/adc_8channel_zyw_1.srcs/constrs_1/imports/SiTCP_Netlist_for_Kintex_UltraScale-master/EDF_SiTCP_constraints.xdc]


synth_design -top top -part xcku040-ffva1156-2-i


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
